name: Build and publish image

on:
  workflow_call:
    inputs:
      tags:
        required: true
        type: string
      platforms:
        required: true
        type: string
      build-args:
        required: true
        type: string
      context:
        required: true
        type: string
      file:
        required: false
        type: string
        default: Dockerfile
    secrets:
      token:
        required: true

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false
    - name: Set up QEMU
      uses: docker/setup-qemu-action@53851d14592bedcffcf25ea515637cff71ef929a # v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v2
      with:
        # Images after this version (>=v0.10) are incompatible with gcr and aws.
        version: v0.9.1  # https://github.com/docker/buildx/issues/1533
    - name: Login to Docker
      run: docker login -u publisher -p ${{ secrets.token }} ghcr.io
    - name: Docker Build
      uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v4
      with:
        push: true
        tags: ${{ inputs.tags }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.context }}/${{ inputs.file }}
